export const PALAVRAS_RUINS = new Set([
    "a", "o", "as", "os", "de", "e", "é", "da", "do", "das", "dos",
    "em", "no", "na", "nos", "nas", "para", "por", "porém", "como", "com",
    "que", "uma", "um", "umas", "uns", "se", "ser", "mas", "mais", "pra",
    "foi", "foram", "isso", "esse", "essa", "aquele", "aquela", "deste",
    "desta", "neste", "nesta", "isto", "isto", "isso", "seja", "são",
    "ao", "aos", "à", "às", "entre", "sobre", "sob", "sem", "após",
    "depois", "durante", "até", "já", "ainda", "quando", "onde", "quem",
    "qual", "quais", "meu", "minha", "meus", "minhas", "seu", "sua",
    "seus", "suas", "nosso", "nossa", "nossos", "nossas", "eu", "tu",
    "ele", "ela", "nós", "vós", "eles", "elas", "me", "te", "lhe", "nos",
    "vos", "lhes", "mim", "ti", "consigo", "conosco", "conosco", "contigo",
    "nele", "nela", "neles", "nelas", "disso", "dessa", "deste", "desta",
    "deles", "delas", "dentre", "assim", "também", "bem", "mal", "muito",
    "pouco", "nenhum", "nenhuma", "poucos", "poucas", "algum", "alguns",
    "alguma", "algumas", "todo", "toda", "todos", "todas", "outro",
    "outra", "outros", "outras", "tal", "tais", "qualquer", "quaisquer",
    "nenhum", "nenhuma", "nenhuns", "nenhumas", "cada", "certo", "certa",
    "certos", "certas", "vários", "várias", "tanto", "tanta", "tantos",
    "tantas", "mesmo", "mesma", "mesmos", "mesmas", "próprio", "própria",
    "próprios", "próprias", "diferente", "diferentes", "respectivo",
    "respectiva", "respectivos", "respectivas", "cujo", "cuja", "cujos",
    "cujas", "onde", "quando", "como", "porque", "pois", "então", "assim",
    "depois", "logo", "agora", "já", "sempre", "nunca", "enquanto",
    "embora", "contudo", "entretanto", "todavia", "exceto", "salvo",
    "apenas", "só", "somente", "inclusive", "até", "mesmo", "inclusive",
    "também", "ainda", "afinal", "talvez", "provavelmente", "certamente",
    "realmente", "definitivamente", "claro", "obviamente", "talvez",
    "ou", "nem", "não", "para", "com", "por", "de", "e", "a", "o"
]);